# 数据源
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.46}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:mall4cloud_auth}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

# 用于token aes签名的key，16位
auth:
  token:
    signKey: -mall4cloud-mall 